CITY_TABLE_SCHEMA = [
    "cityId TEXT PRIMARY KEY",
    "cityNameEn TEXT",
    "cityNameAr TEXT",
]

CATEGORY_TABLE_SCHEMA = [
    "categoryId TEXT PRIMARY KEY",
    "categoryNameEn TEXT",
    "categoryNameAr TEXT",
]

PROPERTY_TABLE_SCHEMA = [
    "propertyTypeId TEXT PRIMARY KEY",
    "propertyTypeNameEn TEXT",
    "propertyTypeNameAr TEXT",
]

LISTING_TABLE_SCHEMA = [
    "listingId TEXT PRIMARY KEY",
    "cityId TEXT",
    "cityNameEn TEXT",
    "cityNameAr TEXT",
    "categoryId TEXT",
    "categoryNameEn TEXT",
    "categoryNameAr TEXT",
    "propertyTypeId TEXT",
    "propertyTypeNameEn TEXT",
    "propertyTypeNameAr TEXT",
    "districtId TEXT",
    "districtNameEn TEXT",
    "districtNameAr TEXT",
    "purpose TEXT",
    "price REAL",
    "priceType TEXT",
    "area REAL",
    "rentType TEXT",
    "relatedQuestions TEXT",
    "developerAgent TEXT",
    "createdBy TEXT",
    "advertiser TEXT",
    "status TEXT",
    "notificationMethods TEXT",
    "promotion TEXT",
    "published TEXT",
    "refreshedAt TEXT",
    "paymentMethod TEXT",
    "code TEXT",
    "createdAt TEXT",
    "updatedAt TEXT",
    "userReportedThisAd TEXT",
    "read TEXT",
    "accept TEXT",
    "reject TEXT",
    "favorite TEXT",
    "regaRawData TEXT",
    "FOREIGN KEY(cityId) REFERENCES city(id)",
    "FOREIGN KEY(categoryId) REFERENCES category(id)",
    "FOREIGN KEY(propertyTypeId) REFERENCES property_type(id)"
]

LISTING_COLUMNS = [
    "listingId",
    "cityId",
    "cityNameEn",
    "cityNameAr",
    "categoryId",
    "categoryNameEn",
    "categoryNameAr",
    "propertyTypeId",
    "propertyTypeNameEn",
    "propertyTypeNameAr",
    "districtId",
    "districtNameEn",
    "districtNameAr",
    "purpose",
    "price",
    "priceType",
    "area",
    "createdBy",
    "advertiser",
    "status",
    "notificationMethods",
    "promotion",
    "published",
    "refreshedAt",
    "paymentMethod",
    "code",
    "createdAt",
    "updatedAt",
    "userReportedThisAd",
    "relatedQuestions",
    "read",
    "accept",
    "reject",
    "favorite",
    "regaRawData",
]

ALL_RAW_COLUMNS_TO_PARSE = [
    "_id",
    "purpose",
    "price",
    "priceType",
    "area",
    "status",
    "published",
    "paymentMethod",
    "code",
    "createdAt",
    "updatedAt",
    "userReportedThisAd",
    "read",
    "accept",
    "reject",
    "favorite",
    "regaRawData",
    "propertyType",
    "city",
    "district",
    "relatedQuestions",
    "createdBy",
    "advertiser",
    "promotion",
    "refreshed",
    "notificationMethods"
]
